[pytest]
filterwarnings =
    ignore::DeprecationWarning:requests.*:
    ignore::DeprecationWarning:httplib2.*:
    ignore:.*urllib3.*:DeprecationWarning
    ignore:.*google\.generativeai.*:FutureWarning
